model:
  pretrained_model_name_or_path: "/data/clx/control-lora-v2-master/ckpt/FLUX.2-klein-base-9B"
  revision: null
  variant: null
  mixed_precision: "bf16"
  enable_npu_flash_attention: false

data:
  instance_data_dir: "/data/clx/data/wenli_data/tile_flux2_klein/resolution512"
  image_column: "image"
  cond_image_column: "target"
  caption_column: "promet"
  resolution: 768
  center_crop: false
  random_flip: true
  train_batch_size: 2
  dataloader_num_workers: 0
  aspect_ratio_buckets: "1024,1024;768,1360;1360,768;880,1168;1168,880;1248,832;832,1248"

training:
  output_dir: "/data/clx/tmp/flux-dreambooth-lora"
  num_train_epochs: 200
  max_train_steps: null
  checkpointing_steps: 500
  checkpoints_total_limit: 20
  gradient_accumulation_steps: 2
  gradient_checkpointing: true
  learning_rate: 5.0e-5
  lr_scheduler: "cosine"
  lr_warmup_steps: 1000
  optimizer: "AdamW"
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 1.0e-04
  max_grad_norm: 1.0
  seed: null

validation:
  validation_prompt: "修复扭曲的建筑立面纹理，使纹理自然、清晰、结构不变"
  validation_image: "test/Image1.png"
  num_validation_images: 4
  validation_epochs: 1
  skip_final_inference: false

lora:
  rank: 16
  alpha: 32
  dropout: 0.0
  target_modules:
    - "to_k"
    - "to_q"
    - "to_v"
    - "to_out.0"
  init_weights: "gaussian"